name: Build Nova APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet and Build Tools
        run: |
          pip install flet
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      - name: Build APK
        run: |
          # Proper Flet build command
          flet build apk

      - name: Upload Artifact
        # Yahan humne v2 ko v4 se replace kar diya hai
        uses: actions/upload-artifact@v4
        with:
          name: Nova-App-Final
          path: build/apk/*.apk
