name: Build Nova APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install flet

      - name: Build APK
        run: |
          # Flet ka official build command
          flet build apk --project "Nova AI"
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Nova-Assistant-APK
          path: build/apk/*.apk
